version: '3.9'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=wheatherdb'
      - 'MYSQL_PASSWORD=thelastofus'
      - 'MYSQL_USER=root'
    ports:
      - '3306'
  redis:
    image: 'redis:latest'
    command: redis-server
    ports:
      - '6379'
