version: '3.9'

volumes:
  db:

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=database'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=admin'
      - 'MYSQL_USER=admin'
    ports:
     - '3306:3306'
    volumes:
    - db:/var/lib/mysql


#  redis:
#    image: 'redis:latest'
#    command: redis-server
#    ports:
#      - '6379:6379'
